(function() {/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=this||self;/*
 Copyright 2022 Glance Networks, Inc.
*/
var k=["6","52","0","1972529788"].slice(0,3).join(".");Uint8Array.prototype.slice||(Uint8Array.prototype.slice=function(a,b){return new Uint8Array(this.subarray(a,b))});
ArrayBuffer.prototype.slice||(ArrayBuffer.prototype.slice=function(a,b){void 0===a&&(a=0);void 0===b&&(b=this.byteLength);a=Math.floor(a);b=Math.floor(b);0>a&&(a+=this.byteLength);0>b&&(b+=this.byteLength);a=Math.min(Math.max(0,a),this.byteLength);b=Math.min(Math.max(0,b),this.byteLength);if(0>=b-a)return new ArrayBuffer(0);var c=new ArrayBuffer(b-a),d=new Uint8Array(c);a=new Uint8Array(this,a,b-a);d.set(a);return c});
var l=navigator.userAgent.toLowerCase(),m=l.match(/(edge)[\s\/:]([\w\d\.]+)?/)||l.match(/(opera|ie|firefox|chrome|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||l.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"rv"===m[1]&&(m[1]="ie");function n(a){for(var b="",c=0;c<a.length;c++)b+=("object"===typeof a[c]?JSON.stringify(a[c]):a[c])+" ";return b.replace(/[\r\n]/g," ").replace("<","&lt;").replace(">","&gt;")}function p(a){window.console&&window.console.log&&(window.GLANCE_COBROWSE?!window.GLANCE_COBROWSE.disableLogging:1)&&window.console.log(n(arguments))}function ba(a){window.console&&window.console.error&&window.console.error(n(arguments))};function r(a,...b){!window.console||!window.console[a]||window.GLANCE_COBROWSE&&window.GLANCE_COBROWSE.disableLogging||(b=b.map(c=>{if("object"===typeof c)try{c=JSON.stringify(c)}catch(d){console.error(d),c="unable to convert object to string"}return"string"===typeof c?c.replace(/[\r\n]/g," ").replace("<","&lt;"):c}),window.console[a](...b))}function t(...a){r("log",...a)}function u(...a){r("error",...a)}function x(...a){t("PRES:",...a)};/*
 Copyright (c) 2022 Glance Networks, Inc.
*/
var y=y||{};window.GLANCE=window.GLANCE||{};window.GLANCE.VERSION="6.52.0.1972529788";window.GLANCE.PATCH="";window.GLANCE.Lib=window.GLANCE.Lib||{};
var z=function(){var a=navigator.userAgent.toLowerCase(),b=navigator.platform.toLowerCase(),c=a.match(/(edge|edg)[\s\/:]([\w\d\.]+)?/)||a.match(/(opera|ie|firefox|chrome|crios|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||a.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"edg"===c[1]&&(c[1]="edge");"crios"===c[1]?c[1]="chrome":"rv"===c[1]&&(c[1]="ie");a={extend:Function.prototype.extend,name:"version"==c[1]?c[3]:c[1],version:"ie"==c[1]&&document.documentMode||parseFloat("opera"==
c[1]&&c[4]?c[4]:c[2]),v:{name:a.match(/ip(?:ad|od|hone)/)||b.match(/mac/)&&0<typeof navigator.maxTouchPoints?"ios":(a.match(/(?:webos|android)/)||b.match(/mac|win|linux/)||["other"])[0]},ga:{na:!!document.evaluate,ia:!!window.g,query:!!document.querySelector,json:!!window.JSON},ha:{},ka:function(){return"ios"==this.v.name||"android"==this.v.name}};document.documentMode&&window.XDomainRequest?(a.name="ie",a.version=document.documentMode):window.navigator&&navigator.appVersion&&-1!=navigator.appVersion.indexOf("MSIE 7.")&&
(a.name="ie",a.version="7");a[a.name]=!0;a[a.name+parseInt(a.version,10)]=!0;a.v[a.v.name]=!0;return a}();function A(){}A.prototype.set=function(a,b){B("clearTimeout",this.g);var c=this;this.g=B("setTimeout",function(){delete c.g;b&&b()},a)};A.prototype.clear=function(){B("clearTimeout",this.g);delete this.g};function C(a,b){if(Array.isArray(a))return(new b.Array(...a)).map(c=>C(c,b));if(null!==a&&"object"===typeof a){const c={};Object.entries(a).forEach(([d,f])=>c[d]=C(f,b));return c}return a}
if(void 0===D)var D=function(a){return E.g?(Array.prototype.toJSON&&(a=C(a,E.g.window)),E.g.window.JSON.stringify(a)):JSON.stringify(a)};C=function(a,b){if(Array.isArray(a))return(new b.Array(...a)).map(c=>C(c,b));if(null!==a&&"object"===typeof a){const c={};Object.entries(a).forEach(([d,f])=>c[d]=C(f,b));return c}return a};
function ca(a){a.J=0;a.K=0;a.V=new A;a.U=new A;a.onclose=function(b){a.V.clear();a.U.clear();a.fa&&a.fa(b)};a.onmessage=function(b){b=JSON.parse(b.data);a.T&&a.T(b);a.ping()};a.B=function(b){b=D(b);a.readyState!==WebSocket.OPEN?u(`Tried to send message on closed websocket: ${b}`):a.send(b)};a.da=function(b){return b&&b.code||0};a.ea=function(b){return b&&b.reason||""};a.la=function(b,c){this.J=b;this.K=c;this.ping()};a.ping=function(){0<a.J&&a.V.set(1E3*a.J,()=>a.B({mtype:"Ping"}));0<a.K&&a.U.set(1E3*
a.K,()=>a.onerror(new Event("WS_PING_TIMEOUT")))}}function da(a){a=new WebSocket(a);ca(a);return a}function ea(a,b){B("setTimeout",function(){ea(a,b)},100)}function F(a,b){if(void 0!==a){var c=c||Object.keys(a);c.forEach(function(d){void 0!==a[d]&&(b[d]=a[d])})}}
function fa(a){var b=a.func.split(".");if(2>b.length)u("ERR_BADINVOKE:");else if("GLANCE"===b[0]||"GLANCE_COBROWSE"===b[0]&&"Custom"===b[1]){for(var c=window[b[0]],d=1;d<b.length;d++)if(c=c[b[d]],!c){u("ERR_UNDEFINVOKE:"+b[d]);return}a.args=a.args||{};a.args.remote=!0;c(a.args)}else u("ERR_BADINVOKE:"+b[0])}function G(){y.ma?this.j=new H("JSON"):this.g=new window.XMLHttpRequest;this.response=null;this.type="JSON"}G.prototype.abort=function(){this.j?this.j.abort():this.g.abort()};
G.prototype.onreadystatechange=function(){if(4==this.g.readyState){B("clearTimeout",this.l);delete this.l;var a="error";if(0==this.g.status)t(this.method+" to "+this.url+" failed: network"),this.h(!0,"connection",this.g.status);else if(200!==this.g.status){u(this.method+" to "+this.url+" failed with status: "+this.g.status);"text"===this.g.responseType&&null!==this.g.responseText&&t(this.g.responseText);if(401===this.g.status||403===this.g.status)a="authorization",this.i&&this.i.ja();this.h(!1,a,
this.g.status)}else{if(""!==this.g.response){if("XML"===this.accept)this.response=this.g.responseXML&&this.g.responseXML.documentElement,null===this.response&&u("Invalid XML response: "+this.g.responseText);else if(this.u){for(var b=new Uint8Array(this.g.responseText.length),c=0;c<this.g.responseText.length;c++)b[c]=this.g.responseText.charCodeAt(c)&255;this.response=new Blob([b],{type:this.g.getResponseHeader("Content-Type")})}else if("blob"===this.g.responseType)this.response=this.g.response;else if(this.g.responseXML)this.response=
ha(this.g.responseXML.childNodes[0].childNodes[0].nodeValue);else if("HTML"===this.accept||"TEXT"===this.accept)this.response=this.g.responseText;else if(this.response=ha(this.g.responseText),null===this.response){t(this.method+" to "+this.url+" failed - can't parse response "+this.g.responseText);this.h(!1,a);return}if(void 0!==this.response.err&&void 0!==this.response.msg){t(this.method+" to "+this.url+" failed with error:"+this.response.err+" "+this.response.msg);this.h(!1,a);return}}this.onsuccess(this.response)}}};
function ha(a){var b=null;try{b=JSON.parse(a)}catch(c){return t("JSON parse failed with error: "+c.toString()+" parsing: "+a),null}return b}G.prototype.getResponseHeader=function(a){return this.g.getResponseHeader(a)};G.prototype.get=function(a,b,c,d,f){this.method="GET";I(this,a,null,b,c,d,f)};
function I(a,b,c,d,f,h,e){a.url=b;a.onsuccess=void 0!==h?h:function(){};a.h=void 0!==e?e:function(){};a.method=a.method||"POST";if(a.j)ia(a.j,b,c,d,f,h,e);else{h=a.C||("JSON"===a.type?"application/json; charset=utf-8":"application/x-www-form-urlencoded; charset=utf-8");if("string"===typeof c)var v=c;else c instanceof Blob?(h=c.type,v=c):c&&(v="JSON"===a.type?D(c):"data="+D(c));z.safari&&a.s&&(a.l=B("setTimeout",function(){t(this.method+" to "+this.url+" failed - timedout (Safari)");this.h(!1,"timedout")}.bind(a),
a.s));a.g.onreadystatechange=function(){a.onreadystatechange()};try{a.g.open(a.method,b,d),void 0!==a.m&&a.g.setRequestHeader("Accept",a.m),void 0!==a.g.setRequestHeader&&"GET"!==a.method&&a.g.setRequestHeader("Content-type",h),a.i&&a.i.ba()?a.g.setRequestHeader("Authorization","Bearer "+a.i.ba()):a.o&&a.g.setRequestHeader("Authorization","Bearer "+a.o),a.g.withCredentials=f,a.g.send(v)}catch(q){t(a.method+" to "+b+" failed with: "+q.toString()),a.h(!1,q.toString())}}}function H(a){this.type=a}
function ia(a,b,c,d,f,h,e){a.onsuccess=h;a.h=e;ea({from:"IFrameProxyRequest",type:a.type,url:b,obj:c,async:d,withcred:f})}H.prototype.abort=function(){H.postMessage({from:"IFrameProxyRequest",abort:!0})};function J(a){this.name=a}function ja(a,b){var c=new Date;c.setUTCHours(c.getUTCHours()+8);try{window.localStorage.setItem(a.name,D(b)),window.localStorage.setItem(a.name+"_exp",c.toGMTString())}catch(d){t("Failed to write cookie: "+a.name)}}
function ka(a){if(!la(a))return null;var b=null;try{b=window.localStorage.getItem(a.name)}catch(c){return t("Failed to read cookie: "+a.name),null}return JSON.parse(b)}function na(a,b){"string"===typeof b&&(b=parseInt(b));var c=new Date;c.setUTCMinutes(c.getUTCMinutes()+b);try{window.localStorage.setItem(a.name+"_exp",c.toGMTString())}catch(d){t("Failed to write cookie: "+a.name)}}
J.prototype.get=function(){if(!la(this))return null;try{return window.localStorage.getItem(this.name)}catch(a){return t("Failed to read cookie: "+this.name),null}};function K(a){try{window.localStorage.removeItem(a.name),window.localStorage.removeItem(a.name+"_exp")}catch(b){t("Failed to delete cookie: "+a.name)}}
function la(a){var b=null;try{b=window.localStorage.getItem(a.name+"_exp")}catch(c){return t("Failed to read cookie: "+a.name),!1}if(!b)return!1;b=new Date(b);return b<new Date?(K(a),!1):!0}
function L(){var a=window;this.g=a.document;this.i=a;var b=[["hidden","visibilitychange"],["mozHidden","mozvisibilitychange"],["webkitHidden","webkitvisibilitychange"],["msHidden","msvisibilitychange"],["oHidden","ovisibilitychange"]];for(a=0;a<b.length;a++)if(b[a][0]in document){this.h=b[a][0];this.j=b[a][1];break}}function M(a){return void 0===a.h?!1:a.g[a.h]}function oa(a,b){a.g.addEventListener(a.j,b)}function E(){}
function B(a,...b){var c=window;return E.g&&c.nodeType?"#document"===c.nodeName?E.g.document[a].apply(c,b):"#document-fragment"===c.nodeName?E.g.DocumentFragment.prototype[a].apply(c,b):E.g.document.body[a].apply(c,b):E.g&&"[object Window]"===c.toString()?E.g.window[a].apply(c,b):c[a].apply(c,b)};function pa(a,b){if(void 0!==a){var c=c||Object.keys(a);c.forEach(function(d){void 0!==a[d]&&(b[d]=a[d])})}}function qa(a){var b={};if(!a)return b;var c=0;for(a=a.attributes;c<a.length;c++){var d=a[c].nodeName.match(/data-(.*)/);d&&2===d.length&&(b[d[1]]=a[c].nodeValue)}return b}function ra(){var a=window.GLANCE_COBROWSE?window.GLANCE_COBROWSE:{},b=document.getElementById("cobrowsescript"),c=document.getElementById("glance-cobrowse");b=qa(b);c=qa(c);pa(b,a);pa(c,a);return a};function N(){}function sa(a,b){a.g={};a.g.ws="www.glance.net";a.g.site="production";a.o=new L;F(ra(),a.g);F(b,a.g);delete a.g.presenceserver;a.C=!1;a.S=new A;a.G=[];a.j=O;a.m=new J("glance_presence");var c=ka(a.m);c&&(0===["visitorid","ws","groupid"].filter(d=>c[d]!==a.g[d]).length?a.i=c.directserver:x("Ignoring glance_presence entry for different webserver, group, or visitor",c.ws,c.groupid,c.visitorid));x("direct server from local storage:",a.i)}var O=1;N.prototype.L=function(){};
function ta(a,b,c,d,f){if(b&&!a.i)p("ERR_NODIRECTSERVER");else{var h=(f||"https")+"://"+(b?a.i:a.g.presenceserver)+"/"+c;d&&(h+="?",["groupid","visitorid"].forEach(function(e){h+=e+"="+a.g[e]+"&"}),h+=`&ver=${k}`);return h}}N.prototype.N=function(a){P(this,"findvisitor","GET",a)};
function Q(a){p("connecting to "+a.i);a.h&&a.h.close();a.h=da(ta(a,!0,"visitorws",!1,"wss"));a.h.W=a.i;a.h.onopen=function(){x("sock onopen, sending connect");a.h.B({type:"connect",authorization:void 0,groupid:a.g.groupid,visitorid:a.g.visitorid,guesttoken:a.g.guesttoken,version:k});a.u=0;x("sending message queue");a.G.forEach(function(b){a.h.B(b)});a.G=[];a.j=3};a.h.T=function(b){p("received:"+D(b));if(a.h){var c=h=>{a.S.clear();if(!a.C&&(a.C=!0,a.onvisitorconn))a.onvisitorconn(h)},d=b.mtype||b.type,
f=b.data;switch(d){case "connected":if(a.g.nokeepalive)break;x("Keepalive interval: "+b.keepalive);a.D||(a.D=window.setInterval(function(){a.h.B({type:"k"})},1E3*b.keepalive));if(a.onconnected)a.onconnected(f);break;case "invoke":"visitor"===a.Y&&fa(f);break;case "redirect":case "serverclose":f||(f=b);a["on"+d](f);break;case "visitorsock":f.connected?c(f):!f.connected&&a.C&&a.S.set(5E3,()=>{a.C=!1;if(a.onvisitorconn)a.onvisitorconn(f)});break;case "visitorconn":f.connected&&c(f);break;default:if(a["on"+
d])a["on"+d](f)}}else x("Ignoring message received after socket close")};a.h.onclose=function(b){a.h===this&&(p(`presence connection closed ${this.da(b)} ${this.ea(b)}`),ua(a),a.s())};a.h.onerror=function(b){a.h===this&&(x("socket error"),a.h.onclose(b))}}
function P(a,b,c,d){function f(q){if(!e.g.isLoadBalanced){var w=q&&(q.directserver||q.direct);w&&(e.i=w,q.httpsport&&(e.i+=":"+q.httpsport),e.L());e.h&&e.i!=e.h.W&&(x("switching connection from "+e.h.W+" to "+e.i),Q(e))}if(d&&d.onsuccess)d.onsuccess(q)}function h(q,w,ma){p(`Presence request: ${b} failed reason: ${w} http status: ${ma||0}`);503===ma&&(ba("Presence service unavailable"),e.R=!0,w="serviceunavailable");if(d.onfail)d.onfail(w);else R(e,{error:"connfail",detail:w})}if(!a.R){var e=a,v=new G;
v.i=void 0;v.method=c;p(b,JSON.stringify(d));va(a,function(){e.g.presenceserver&&I(v,ta(e,!1,b,!0),d.data?d.data:{},!0,!1,f,h)})}}
function va(a,b){if(a.g.presenceserver)b();else{var c=new J("glance_visitor_settings_"+a.g.groupid+"_"+a.g.site),d=ka(c);if(d)a.g.presenceserver=d.presenceserver,a.g.isLoadBalanced=d.presencesettings.isPresenceLoadBalanced,a.g.isLoadBalanced&&(a.i=a.g.presenceserver),a.g.presenceserver||p("PRES_DISABLED (from cache)"),b();else{d=new G;var f="https://"+a.g.ws+"/services/authorizationservice/GetVisitorSettings3?groupid="+a.g.groupid+"&site="+a.g.site+"&service=presence";d.method="GET";I(d,f,null,!0,
!1,h=>{a.g.presenceserver=h.presenceUrl;h.isPresenceLoadBalanced&&(a.g.isLoadBalanced=h.isPresenceLoadBalanced,a.i=h.presenceUrl);x("presence service: "+a.g.presenceserver);a.g.presenceserver||p("PRES_DISABLED");var e={};e.presenceserver=a.g.presenceserver;e.presencesettings=h;ja(c,e);na(c,1440);return b()},(h,e)=>{p("PRES_UNAVAILABLE "+e);b()})}}}function S(a){x("closewebsocket");a.h&&a.h.close();ua(a)}
function ua(a){a.D&&(window.clearInterval(a.D),delete a.D);a.j=O;a.g.isLoadBalanced||delete a.i;delete a.h}function T(a,b){p("sending",b.type,a.j);3===a.j?(x("sending message: "+JSON.stringify(b)),a.h.B(b)):(x("queuing message: "+JSON.stringify(b)),a.G.push(b),a.connect())}N.prototype.ca=function(){return this.g.visitorid};N.prototype.getVisitorId=N.prototype.ca;N.prototype.X=function(a){let b=3===this.j;b&&this.disconnect();this.g.visitorid=a;(b||"api"!==this.g.presence)&&this.connect()};
N.prototype.setVisitorId=N.prototype.X;
N.prototype.connect=function(){if(!this.R)if(this.g.visitorid)if(this.j!==O)x("connect() called when already connecting or connected");else{this.j=2;x("connect");var a=this;this.onscaledown=function(){a.disconnect();a.connect()};this.onredirect=function(b){x("Connected to wrong instance:",JSON.stringify(b),"current direct server:",this.i);this.m&&b.direct!==this.i&&(K(this.m),this.m=new J("glance_presence"),this.disconnect(),this.s())};this.onserverclose=function(){a.disconnect();if(a.onclose)a.onclose()};
va(this,()=>{p("visitor settings loaded");this.i?Q(this):this.N({onsuccess:function(){p("found visitor, connect");Q(a)},onfail:function(b){a.j=O;R(a,{error:"connfail",detail:b})}})})}else p("CONN_NOVISITORID")};N.prototype.connect=N.prototype.connect;N.prototype.disconnect=function(){S(this);this.m&&K(this.m)};N.prototype.disconnect=N.prototype.disconnect;
N.prototype.s=function(){x(`delayed reconnect.  count: ${this.u||0} connstate: ${this.j}`);this.M||(this.u=this.u||0,this.u++,this.M=window.setTimeout(()=>{delete this.M;this.connect()},3>=this.u?5E3:6E4))};N.prototype.I=function(){return 3===this.j};N.prototype.isconnected=N.prototype.I;function R(a,b){p("Error: ",JSON.stringify(b));a.O&&a.O(b);if(a.onerror)a.onerror(b)}N.prototype.aa=function(a,b){T(this,{type:a,data:b})};N.prototype.fire=N.prototype.aa;function U(a){sa(this,a);this.Y="visitor";this.o=new L;this.H=!1;var b=this;B("addEventListener","focus",function(){x("presence visitor got focus event");b.F=!1;b.P&&b.A()},void 0);oa(this.o,function(){if(!b.H&&(x("visibility:",M(b.o)?"hidden":"visible"),(b.P||b.I())&&!b.F)){var c={type:"visibility"};c.data={visibility:M(b.o)?"hidden":"visible"};T(b,c);M(b.o)&&S(b)}});U.instance=this}var wa=U,V=["GLANCE","Presence","Visitor"],W=aa;V[0]in W||"undefined"==typeof W.execScript||W.execScript("var "+V[0]);
for(var X;V.length&&(X=V.shift());)V.length||void 0===wa?W[X]&&W[X]!==Object.prototype[X]?W=W[X]:W=W[X]={}:W[X]=wa;U.prototype=new N;U.prototype.L=function(){x("caching direct server:",this.i);var a={};a.directserver=this.i;a.groupid=this.g.groupid;a.visitorid=this.g.visitorid;a.ws=this.g.ws;ja(this.m,a);na(this.m,20)};U.prototype.s=function(){M(this.o)||N.prototype.s.bind(this)()};
U.prototype.A=function(a){x("presence");if(this.g.visitorid){this.l=this.l||{};for(var b in this.g)0===b.indexOf("user-")&&(this.l[b.substring(5)]=this.g[b]);this.l.url=window.location.href;this.l.browser=z.name;this.l.browserver=z.version;this.l.platform=z.v.name;(a=a&&a.data)&&F(a,this.l);this.F||(a={type:"presence"},a.data=this.l,T(this,a),this.P=!0);this.O=function(c){"connfail"===c.error&&this.s()}}else p("PRES_NOVISITORID")};U.prototype.presence=U.prototype.A;
U.prototype.Z=function(a){var b=this;this.H=!0;P(this,"uniquevisitor","GET",{onsuccess:function(c){p("got unique visitor id",c.visitorid);b.g.visitorid=c.visitorid;b.g.guesttoken=c.guesttoken;b.g.timeout=c.timeout||300;if(b.onuniqueid)b.onuniqueid(c.uniqueid,b.g.timeout);b.connect();a&&a.data&&b.A({data:a.data})},onfail:function(c){R(b,{error:"connfail",detail:c})}})};U.prototype.connectUnique=U.prototype.Z;
U.prototype.$=function(){this.H?this.I()?(this.disconnect(),this.A()):R(this,{error:"connfail",detail:"extend"}):console.error("ERR_EXTEND_UNIQUE")};U.prototype.extendUnique=U.prototype.$;U.setVisitorId=function(a){U.instance&&U.instance.X(a)};U.prototype.N=function(a){this.g.isLoadBalanced||(a.data={},P(this,"presence","POST",a))};U.prototype.onblur=function(){p("BLURRED");this.F=!0;S(this)};var xa=!1;function Y(){if(!xa){xa=!0;var a=ra();a.presence&&"api"!==a.presence&&(new U).A()}}var Z=new L;
Z.i.addEventListener&&(document.readyState.match(/complete/)?Y():(Z.i.addEventListener("load",Y),Z.g.addEventListener("DOMContentLoaded",Y,!1)));}).call(window);
//# sourceMappingURL=map.js.map
