# Generated by Django 5.0.4 on 2024-10-04 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='benfitx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=50, null=True)),
                ('accname', models.CharField(blank=True, max_length=50, null=True)),
                ('accnum', models.CharField(blank=True, max_length=50, null=True)),
                ('bankname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('swiftcode', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='depositex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=50, null=True)),
                ('Amount', models.CharField(blank=True, max_length=50, null=True)),
                ('appoved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='intertransferx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=50, null=True)),
                ('accname', models.CharField(blank=True, max_length=50, null=True)),
                ('accnum', models.CharField(blank=True, max_length=50, null=True)),
                ('bankname', models.CharField(blank=True, max_length=50, null=True)),
                ('swiftcode', models.CharField(blank=True, max_length=50, null=True)),
                ('ibannumber', models.CharField(blank=True, max_length=50, null=True)),
                ('ountry', models.CharField(blank=True, max_length=50, null=True)),
                ('Amount', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('appoved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=50, null=True)),
                ('Types', models.CharField(blank=True, max_length=50, null=True)),
                ('Amount', models.CharField(blank=True, max_length=50, null=True)),
                ('NetIncome', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('appoved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='localtransferx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=50, null=True)),
                ('accname', models.CharField(blank=True, max_length=50, null=True)),
                ('accnum', models.CharField(blank=True, max_length=50, null=True)),
                ('bankname', models.CharField(blank=True, max_length=50, null=True)),
                ('Amount', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('appoved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='siteedit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('domain', models.CharField(blank=True, default=models.CharField(blank=True, max_length=50, null=True), max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('dis', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('image1', models.TextField(blank=True, null=True)),
                ('idx', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=40, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('account_type', models.CharField(blank=True, max_length=40, null=True)),
                ('preferred_currency', models.CharField(blank=True, max_length=40, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('benfit', models.ManyToManyField(blank=True, to='app.benfitx')),
                ('deposite', models.ManyToManyField(blank=True, to='app.depositex')),
                ('intertransfer', models.ManyToManyField(blank=True, to='app.intertransferx')),
                ('loan', models.ManyToManyField(blank=True, to='app.loan')),
                ('localtransfer', models.ManyToManyField(blank=True, to='app.localtransferx')),
            ],
        ),
    ]
