# Generated by Django 5.0.4 on 2024-10-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_accountnum_account_zipcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='marital_status',
        ),
    ]
