# Generated by Django 5.0.4 on 2024-10-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_account_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='appoved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='disable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='benfitx',
            name='appoved',
            field=models.BooleanField(default=False),
        ),
    ]
