# Generated by Django 5.0.4 on 2024-10-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_account_appoved_account_disable_benfitx_appoved'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='swiftcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
