# Generated by Django 5.0.4 on 2024-10-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_benfitx_appoved_alter_depositex_appoved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benfitx',
            name='appoved',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='depositex',
            name='appoved',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='intertransferx',
            name='appoved',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='localtransferx',
            name='appoved',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
