# Generated by Django 5.0.4 on 2024-10-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_benfitx_appoved_alter_depositex_appoved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benfitx',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='depositex',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='intertransferx',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='localtransferx',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
