# Generated by Django 5.0.4 on 2024-10-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_benfitx_date_depositex_date_intertransferx_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='localtransferx',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
