# Generated by Django 5.0.4 on 2024-10-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_benfitx_date_alter_depositex_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositex',
            name='method',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
