# Generated by Django 5.0.4 on 2024-10-05 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_depositex_method'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='loan',
            new_name='loanx',
        ),
    ]
