# Generated by Django 5.0.4 on 2024-10-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_loan_loanx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benfitx',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='depositex',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='intertransferx',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='loanx',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='localtransferx',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='intertransferx',
            name='uuid',
            field=models.CharField(blank=True, default='6e28ce5e8680', max_length=50, null=True),
        ),
    ]
