# Generated by Django 4.2.16 on 2024-10-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_intertransferx_accnum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localtransferx',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='intertransferx',
            name='Description',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='intertransferx',
            name='accnum',
            field=models.CharField(blank=True, default=3319221654398, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intertransferx',
            name='swiftcode',
            field=models.CharField(blank=True, default='EYYIFLM6', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intertransferx',
            name='uuid',
            field=models.CharField(blank=True, default='16a079c61b19', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loanx',
            name='Description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localtransferx',
            name='Description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localtransferx',
            name='accnum',
            field=models.CharField(blank=True, default=8789456021106, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localtransferx',
            name='uuid',
            field=models.CharField(blank=True, default='8a5545f1b', max_length=50, null=True),
        ),
    ]
